# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DevDeploy
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo Build Dev Job
      - bash: echo $(PipelineLevelVariable)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourceDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
#- stage: QADeploy
#  dependsOn: DevDeploy 
#  jobs:
#    - job: QADeployJob
#      steps:
#      - bash: echo Build QA Job
#- stage: ProdDeploy
#  variables:
#    environment: Prod
#  dependsOn: 
#    - DevDeploy 
#    - QADeploy
#  jobs:
#    - job: ProdDeployJob
#      steps:
#      - bash: echo Build Prod Job
#      - bash: echo $(environment)DeployJob
