# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DevDeploy
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo Build Dev Job
- stage: QADeploy
  jobs:
    - job: QADeployJob
      steps:
      - bash: echo Build QA Job
- stage: ProdDeploy
  jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo Build Prod Job
